# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

issues:
  max-same-issues: 0

linters:
  default: none
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
    - govet
    - copyloopvar

formatters:
  enable:
    - gofmt

run:
  timeout: 3m
