name: Docs

on:
  pull_request:
    branches:
      - "main"
    types: [ opened, synchronize ]

jobs:
  docs:
    name: Validate Docs
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:

      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install Go dependencies
        run: go mod tidy

      - name: Install build dependencies
        run: sudo apt update && sudo apt install gcc libc-dev -y

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.9.2'
          terraform_wrapper: false

      - name: Generate documentation
        run: |
          make create-docs-linux PARAM_CC="gcc" PARAM_CGO_LDFLAGS="'-s -w -lm'"

      - name: Git diff
        run: |
          git diff --compact-summary --exit-code examples docs || \
            (echo; echo "Unexpected difference in directories [/examples, /docs] after code generation. Run 'go generate ./...' command and commit."; exit 1)
