name: Release

on:
  workflow_dispatch:

jobs:

  create-release:
    name: Create Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:

      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep 'ProviderVersion =' version/version.go | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+(-pre)?)".*/\1/')
          echo "version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Download Artifacts
        uses: bitwarden/gh-actions/download-artifacts@main
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          path: artifacts
          skip_unpack: false

      - name: Generate Checksum File
        id: checksum
        env:
          VERSION: ${{ steps.current-version.outputs.version }}
        run: |
          MODULE_NAME=$(grep "^module" go.mod | awk -F'/' '{print $NF}')
          CHECKSUM_FILE="${MODULE_NAME}_${VERSION}_SHA256SUMS"
          shasum -a 256 artifacts/*.zip | sed 's|artifacts/||' > "$CHECKSUM_FILE"
          echo "module_name=$MODULE_NAME" >> "$GITHUB_OUTPUT"
          echo "checksum_file=$CHECKSUM_FILE" >> "$GITHUB_OUTPUT"

      - name: Log in to Azure
        uses: bitwarden/gh-actions/azure-login@main
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Get Azure Key Vault secrets
        id: get-kv-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: gh-tf-provider-bw-secret
          secrets: "GPG-PRIVATE-KEY,GPG-PASSPHRASE,GPG-KEY-ID"

      - name: Log out from Azure
        uses: bitwarden/gh-actions/azure-logout@main

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ steps.get-kv-secrets.outputs.GPG-PRIVATE-KEY }}
          passphrase: ${{ steps.get-kv-secrets.outputs.GPG-PASSPHRASE }}

      - name: Prepare Manifest File
        id: manifest
        env:
          MODULE_NAME: ${{ steps.checksum.outputs.module_name }}
          VERSION: ${{ steps.current-version.outputs.version }}
          CHECKSUM_FILE: ${{ steps.checksum.outputs.checksum_file }}
        run: |
          MANIFEST_FILE="${MODULE_NAME}_${VERSION}_manifest.json"
          cp terraform-registry-manifest.json "$MANIFEST_FILE"
          shasum -a 256 "$MANIFEST_FILE" >> "$CHECKSUM_FILE"
          echo "manifest_file=$MANIFEST_FILE" >> "$GITHUB_OUTPUT"

      - name: Sign Checksum File
        env:
          GPG_KEY_ID: ${{ steps.get-kv-secrets.outputs.GPG-KEY-ID }}
          CHECKSUM_FILE: ${{ steps.checksum.outputs.checksum_file }}
        run: |
          gpg --detach-sign --local-user "${GPG_KEY_ID}" --output "${CHECKSUM_FILE}.sig" "${CHECKSUM_FILE}"

      - name: Release
        uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
        with:
          name: v${{ steps.current-version.outputs.version }}
          commit: ${{ github.sha }}
          tag: v${{ steps.current-version.outputs.version }}
          generateReleaseNotes: true
          artifacts: "artifacts/*.zip,
              ${{ steps.manifest.outputs.manifest_file }},
              ${{ steps.checksum.outputs.checksum_file }},
              ${{ steps.checksum.outputs.checksum_file }}.sig"
